# Jekyll configuration for GitHub Pages
title: "Tnuctipun"
description: "Type-safe MongoDB query and update builder for Rust"
baseurl: "/tnuctipun"
url: "https://cchantep.github.io"

# Theme - using minima which is GitHub Pages compatible
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Minima theme settings
header_pages:
  - index.md
  - user-guide/index.md

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
  input: GFM

# Collections for examples
collections:
  examples:
    output: true
    permalink: /examples/:name/

# Defaults for minima theme
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "user-guide"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "examples"
      type: "pages"  
    values:
      layout: "page"
